name = "lapce-rust"
display-name = "Rust"
description = "Rust for Lapce: powered by Rust Analyzer"
version = "0.1.7"
author = "Lapce"
repository = "lapce/lapce-rust"
wasm = "lapce-rust.wasm"

[configuration]
language_id = "rust"
[configuration.options.diagnostics]
enable = false
enableExperimental = false
